// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBiaQ8aYGtMbNwX0QzupodXlAUVKQMiHE',
    appId: '1:829250018583:android:8130780dd8162a53016b52',
    messagingSenderId: '829250018583',
    projectId: 'confiable-fe601',
    databaseURL: 'https://confiable-fe601-default-rtdb.firebaseio.com',
    storageBucket: 'confiable-fe601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwr6bFCrRm90hOsD1H7Wfg8nwladGiJAk',
    appId: '1:829250018583:ios:807e02220b8a9a4d016b52',
    messagingSenderId: '829250018583',
    projectId: 'confiable-fe601',
    databaseURL: 'https://confiable-fe601-default-rtdb.firebaseio.com',
    storageBucket: 'confiable-fe601.appspot.com',
    androidClientId: '829250018583-goe765t13n8nkb18sl9tjouu3746cv20.apps.googleusercontent.com',
    iosClientId: '829250018583-7e7129iilolbr6fl1lb15fi4vgk3kmv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cienConductor',
  );

}